# CodeMap vocabulary grammar — GBNF whose TERMINALS are the pack's real vocabulary
# (PIPELINE.md round-2 lever 1). With this grammar loaded, inventing a nonexistent entity
# name or sub id is UNREPRESENTABLE at decode time. Compile/load ONCE per pack version
# (llama-server --grammar-file); never rebuild per request — a ~1.4k-terminal enum is the
# expensive-to-compile, cheap-to-run kind (XGrammar 2411.15100).
#
# Grammar removes INVENTION, not wrong SELECTION — a wrong-but-real name is still
# grammatical. Selection is trained (open-book pairs) and execution-filtered.
#
# Sources of truth (never duplicated here): app/dsl.py VERBS for the verb set + arities,
# graph/pack/entities.csv for entity names, graph/pack/l2_navigators.jsonl for routable
# sub ids, engine health kinds mirrored from app/engine.py (asserted in test_app terminals).
#
# Usage: PYTHONUTF8=1 python graph/scripts/gbnf_vocab.py   (writes graph/pack/codemap_vocab.gbnf)

import csv
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PACK = os.path.join(HERE, "..", "pack")
sys.path.insert(0, os.path.join(HERE, "..", "..", "app"))
from dsl import VERBS, parse  # noqa: E402

# Arg domains per verb — the shape half lives in dsl.VERBS (arity), the domain half here.
# _DRIFT_GUARD below fails the build if dsl.VERBS gains/loses a verb this table doesn't know.
DOMAINS = {
    "map": [],
    "enter": ["sub"],
    "find": ["free"],          # the legitimate fuzzy verb — free text BY DESIGN
    "impact": ["entity", "depth?"],
    "flow": ["entity", "depth?"],
    "seam": ["sub", "sub"],
    "cohort": ["entity"],
    "spine": ["sub"],
    "health": ["hkind"],
    "read": ["entity"],
    "cache": ["free"],
    "answer": ["free"],
    "pass": ["free"],
}
HKINDS = ["coupling", "hubs"]  # mirror of app/engine.py health(); drift caught by smoke gold
DEPTHS = ["1", "2", "3"]
_NAME_OK = re.compile(r"^[A-Za-z0-9._$-]+$")  # GBNF literals need no escaping in this set


def load_vocab():
    with open(os.path.join(PACK, "entities.csv"), encoding="utf-8") as f:
        names = sorted({r["name"] for r in csv.DictReader(f)})
    subs = []
    with open(os.path.join(PACK, "l2_navigators.jsonl"), encoding="utf-8") as f:
        for line in f:
            r = json.loads(line)
            if r.get("routable"):
                subs.append(str(r["sub_id"]))
    subs = sorted(set(subs), key=int)
    return names, subs


def emit(names, subs):
    bad = [n for n in names if not _NAME_OK.match(n)]
    assert not bad, f"names need GBNF escaping (extend the emitter first): {bad[:5]}"
    alts = lambda xs: " | ".join(f'"{x}"' for x in xs)  # noqa: E731
    g = [
        "# generated by gbnf_vocab.py — terminals ARE the pack vocabulary; regenerate on",
        "# every pack export. Invention of names/ids is unrepresentable under this grammar.",
        "root ::= mapx | enterx | findx | impactx | flowx | seamx | cohortx | spinex | healthx | readx | cachex | answerx | passx",
        'mapx ::= "map()"',
        'enterx ::= "enter(" sub ")"',
        'findx ::= "find(" free ")"',
        'impactx ::= "impact(" entity depthtail ")"',
        'flowx ::= "flow(" entity depthtail ")"',
        'depthtail ::= ("," ws depth)?',
        'seamx ::= "seam(" sub "," ws sub ")"',
        'cohortx ::= "cohort(" entity ")"',
        'spinex ::= "spine(" sub ")"',
        'healthx ::= "health(" hkind ")"',
        'readx ::= "read(" entity ")"',
        'cachex ::= "cache(" free ")"',
        'answerx ::= "answer(" free ")"',
        'passx ::= "pass(" free ")"',
        f"sub ::= {alts(subs)}",
        f"hkind ::= {alts(HKINDS)}",
        f"depth ::= {alts(DEPTHS)}",
        # free text: quoted (commas/parens allowed inside) or bare without , ( ) —
        # fixes the v0 mismatch where the parser accepted quoted commas the grammar banned
        'free ::= "\\"" [^"]* "\\"" | [^,()\\n]+',
        f"entity ::= {alts(names)}",
        'ws ::= " "?',
    ]
    return "\n".join(g) + "\n"


def check(names, subs, grammar):
    # 1. verb-set drift: every dsl verb has a domain row, arities agree with the shapes
    assert set(DOMAINS) == set(VERBS), f"verb drift: {set(DOMAINS) ^ set(VERBS)}"
    for v, doms in DOMAINS.items():
        lo = sum(1 for d in doms if not d.endswith("?"))
        hi = len(doms)
        a = VERBS[v]
        want = (lo, hi) if lo != hi else lo
        assert a == want, f"arity drift on {v}: dsl={a} domains={want}"
    # 2. coverage: every name and sub appears verbatim exactly once in its rule
    erule = next(l for l in grammar.splitlines() if l.startswith("entity ::="))
    srule = next(l for l in grammar.splitlines() if l.startswith("sub ::="))
    assert all(f'"{n}"' in erule for n in names), "entity terminal missing"
    assert all(f'"{s}"' in srule for s in subs), "sub terminal missing"
    # 3. round-trip: one canonical expression per verb, built from REAL vocab, must parse
    e0, s0, s1 = names[0], subs[0], subs[1]
    samples = [
        "map()", f"enter({s0})", 'find("magic link")', f"impact({e0})",
        f"impact({e0}, 2)", f"flow({e0})", f"seam({s0}, {s1})", f"cohort({e0})",
        f"spine({s0})", "health(coupling)", f"read({e0})", 'cache("how do consents work")',
        'answer("text, with commas")', 'pass("needs-content-read: only the file body knows")',
    ]
    for x in samples:
        parse(x)  # raises on failure
    return len(samples)


def main():
    names, subs = load_vocab()
    grammar = emit(names, subs)
    n = check(names, subs, grammar)
    out = os.path.join(PACK, "codemap_vocab.gbnf")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(grammar)
    sha = hashlib.sha256(grammar.encode()).hexdigest()[:16]
    print(f"GBNF OK: {len(names)} entities, {len(subs)} subs, {len(HKINDS)} health kinds, "
          f"{n} round-trip samples parsed. {len(grammar)} bytes, sha {sha} -> {out}")


if __name__ == "__main__":
    main()
