"""Render the generated parts of `.agents/` and the per-harness agent shims from their sources.

    PYTHONUTF8=1 python applications/CodeMap/tools/agents/sync_agents.py [--check] [--pack applications/CodeMap/graph/pack]

The skills in `.agents/skills/<name>/SKILL.md` are written by hand and are the single source of
truth. Everything below is generated, so edit the source and run this script, never the output:

- `.claude/agents/<agent>.md`: Claude Code subagent shims (Cursor and VS Code read the same folder).
  Frontmatter from the skill; the body tells the agent which skill files to read first.
- `.agents/skills/{ladybug-graph,erdos-architect}/references/tools.md`: the MCP tool contract, from
  `remote/engine_mcp.py`, `graph/delta/pack_mcp.py` and `app/dsl.py`.
- `.agents/skills/ladybug-graph/references/schema.md`: tables, columns, edge kinds and counts, read
  from the pack database (needs the pack).
- `.agents/skills/erdos-architect/references/graph-map.md`: the L1 index, the L2 navigators and the
  curation notes, rendered from the pack the way the served navigator prompt renders them (needs the pack).

`--check` renders in memory and exits 1 when a committed file differs; outputs that need the pack
are skipped (and reported) when the pack is absent. Deterministic: same inputs, same bytes.
"""

import argparse
import csv
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.dirname(os.path.dirname(HERE))                  # applications/CodeMap
ROOT = os.path.dirname(os.path.dirname(R))                   # the repository
SKILLS = os.path.join(ROOT, ".agents", "skills")
CLAUDE_AGENTS = os.path.join(ROOT, ".claude", "agents")
for p in (R, os.path.join(R, "app"), os.path.join(R, "graph", "delta"), os.path.join(R, "tools", "prompt")):
    if p not in sys.path:
        sys.path.insert(0, p)

GENERATED = "<!-- generated by applications/CodeMap/tools/agents/sync_agents.py; edit the source it names, not this file -->"

# agent -> the files it reads first, in order (paths relative to the repository root)
AGENTS = {
    "hypatia-indexer": [".agents/skills/ladybug-graph/SKILL.md", ".agents/skills/hypatia-indexer/SKILL.md"],
    "grothendieck-organizer": [".agents/skills/ladybug-graph/SKILL.md", ".agents/skills/grothendieck-organizer/SKILL.md"],
    "erdos-architect": [".agents/skills/erdos-architect/SKILL.md", ".agents/skills/erdos-architect/references/graph-map.md",
                        ".agents/skills/erdos-architect/references/tools.md"],
}


# ----------------------------------------------------------------------------- frontmatter

def split_frontmatter(text):
    """-> (fields, body). A small subset of YAML: `key: value` lines, double-quoted or bare values,
    and one level of indented `key: value` under a bare `key:` (kept as a dict)."""
    text = text.replace("\r\n", "\n")
    if not text.startswith("---\n"):
        return {}, text
    end = text.index("\n---\n", 4)
    fields, current = {}, None
    for line in text[4:end].split("\n"):
        if not line.strip():
            continue
        indented = line.startswith("  ")
        key, _, value = line.strip().partition(":")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = value[1:-1]
        if indented and current is not None:
            fields[current][key] = value
        elif value == "":
            current = key
            fields[key] = {}
        else:
            current = None
            fields[key] = value
    return fields, text[end + 5:]


def skill(name):
    with open(os.path.join(SKILLS, name, "SKILL.md"), encoding="utf-8") as f:
        return split_frontmatter(f.read())


# ----------------------------------------------------------------------------- renderers

def render_shim(name):
    fields, _ = skill(name)
    reads = "\n".join(f"{i}. `{p}`" for i, p in enumerate(AGENTS[name], 1))
    return (f"---\nname: {name}\ndescription: \"{fields['description']}\"\nmodel: inherit\n---\n{GENERATED}\n"
            f"<!-- source: .agents/skills/{name}/SKILL.md -->\n\n"
            f"Before anything else, read these files in full and follow them; together they are your operating manual:\n\n"
            f"{reads}\n\n"
            f"Paths are relative to the root of the graph-theory-system-modeling repository. When a file and this note "
            f"disagree, the file wins. Return the report or answer the manual defines.\n")


def render_tools():
    from remote.engine_mcp import TOOLS as ENGINE
    import pack_mcp
    import dsl
    out = [GENERATED, "<!-- sources: remote/engine_mcp.py, graph/delta/pack_mcp.py, app/dsl.py -->", "",
           "# The CodeMap graph tools", "",
           "Both servers are read-only stdio MCP servers over the pack; start them with `CODEMAP_PACK_DIR` set to the pack "
           "directory and an absolute script path (Claude Code does not honour a working directory in an MCP config).", "",
           "## engine (`applications/CodeMap/remote/engine_mcp.py`)", ""]
    for t in ENGINE:
        out.append(f"- **`{t['name']}`**({', '.join(t['inputSchema']['properties'])}) — {t['description']}")
    out += ["", "## pack (`applications/CodeMap/graph/delta/pack_mcp.py`)", ""]
    for t in pack_mcp.TOOLS:
        out.append(f"- **`{t['name']}`**({', '.join(t['inputSchema']['properties'])}) — {t['description']}")
    out += ["", "## Verbs for `engine_step`", "", "| verb | arguments |", "|---|---|"]
    for verb, arity in dsl.VERBS.items():
        if verb in ("answer", "pass", "cache"):
            continue
        args = {0: "none", 1: "one", 2: "two"}.get(arity, "one or two") if not isinstance(arity, tuple) else f"{arity[0]} or {arity[1]}"
        out.append(f"| `{verb}` | {args} |")
    out += ["", "`health` takes `coupling` (subsystems by external ratio) or `hubs` (entities by in-degree). "
                "`answer`, `pass` and `cache` belong to the served navigator's loop and are not for agents.", ""]
    return "\n".join(out)


def render_schema(pack):
    import real_ladybug as lb
    db = lb.Database(os.path.join(pack, "codemap.lbdb"), read_only=True)
    con = lb.Connection(db)

    def rows(stmt):
        r = con.execute(stmt)
        out = []
        while r.has_next():
            out.append(r.get_next())
        return out

    man = json.load(open(os.path.join(pack, "manifest.json"), encoding="utf-8"))
    out = [GENERATED, "<!-- source: the pack database and manifest -->", "", "# Pack schema", "",
           f"Pack `{man.get('pack_version')}`, built `{man.get('built_at')}`, dialect `{man.get('dialect')}`.", "",
           "Indexed commits: " + ", ".join(f"{k} `{v}`" for k, v in sorted((man.get("indexed_sha") or {}).items())) + ".", "",
           "## Tables", ""]
    for _, name, kind, _, _ in sorted(rows("CALL show_tables() RETURN *"), key=lambda r: r[1]):
        out += [f"### `{name}` ({kind.lower()})", "", "| column | type | primary key |", "|---|---|---|"]
        for info in rows(f"CALL table_info('{name}') RETURN *"):
            pk = info[4] if isinstance(info[4], bool) else ""
            out.append(f"| `{info[1]}` | {info[2]} | {'yes' if pk is True else ''} |")
        out.append("")
    out += ["## Counts", "", "| what | n |", "|---|---|"]
    for k, v in sorted((man.get("counts") or {}).items()):
        out.append(f"| {k} | {v} |")
    out += ["", "## Edge kinds (`Dep.rel`)", "", "| rel | edges |", "|---|---|"]
    for rel, n in sorted(rows("MATCH (:Entity)-[r:Dep]->(:Entity) RETURN r.rel, count(*)"), key=lambda r: (-r[1], r[0])):
        out.append(f"| `{rel}` | {n} |")
    out += ["", "## Entity layers", "", "| layer | entities |", "|---|---|"]
    for layer, n in sorted(rows("MATCH (e:Entity) RETURN e.layer, count(*)"), key=lambda r: (-r[1], str(r[0]))):
        out.append(f"| `{layer}` | {n} |")
    out += ["", "## CSV headers", ""]
    for name in ("entities.csv", "edges.csv", "edges_lb.csv", "hyperedges.csv"):
        path = os.path.join(pack, name)
        if os.path.exists(path):
            with open(path, encoding="utf-8", newline="") as f:
                out.append(f"- `{name}`: {', '.join(next(csv.reader(f)))}")
    out.append("")
    return "\n".join(out)


def render_graph_map(pack):
    from engine import Engine
    from build_navigator import render_l2
    engine = Engine(pack_dir=pack)
    l1 = engine.map()
    man = json.load(open(os.path.join(pack, "manifest.json"), encoding="utf-8"))
    caveats = l1.get("caveats")
    if isinstance(caveats, (list, tuple)):
        caveats = " | ".join(str(c) for c in caveats)
    notes_path = os.path.join(pack, "curation_notes.md")
    notes = open(notes_path, encoding="utf-8").read().strip() if os.path.exists(notes_path) else "none"
    heads = ", ".join(f"{k} `{v[:10]}`" for k, v in sorted((man.get("indexed_sha") or {}).items()))
    text = "\n".join([
        GENERATED, "<!-- source: the pack (l1_master.json, l2_navigators.jsonl, curation_notes.md, manifest.json) -->", "",
        "# The checkItOut graph map", "",
        f"Pack `{man.get('pack_version')}`, built `{man.get('built_at')}`, indexing {heads}. "
        "Subsystem ids are in brackets; GROUP rows contain child subsystems. The prose was written when the pack was built: "
        "when it and the code disagree, the code wins.", "",
        "## L1 — subsystem index", "", (l1.get("index") or "").strip(), "",
        "## Global caveats", "", str(caveats or "none"), "",
        "## L2 — one navigator per subsystem", "", render_l2(engine.l2), "",
        "## Curation notes (newest word on where things live)", "", notes, ""])
    return text.replace("\r\n", "\n")


# ----------------------------------------------------------------------------- targets

def targets(pack):
    """-> ({path: text}, [skipped reasons])."""
    out, skipped = {}, []
    for name in AGENTS:
        out[os.path.join(CLAUDE_AGENTS, f"{name}.md")] = render_shim(name)
    tools = render_tools()
    for s in ("ladybug-graph", "erdos-architect"):
        out[os.path.join(SKILLS, s, "references", "tools.md")] = tools
    if pack and os.path.exists(os.path.join(pack, "codemap.lbdb")):
        out[os.path.join(SKILLS, "ladybug-graph", "references", "schema.md")] = render_schema(pack)
        out[os.path.join(SKILLS, "erdos-architect", "references", "graph-map.md")] = render_graph_map(pack)
    else:
        skipped.append(f"no pack at {pack}: schema.md and graph-map.md not rendered")
    return out, skipped


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--pack", default=os.path.join(R, "graph", "pack"))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    files, skipped = targets(a.pack)
    stale = []
    for path, text in sorted(files.items()):
        current = open(path, encoding="utf-8").read().replace("\r\n", "\n") if os.path.exists(path) else None
        if current == text:
            continue
        if a.check:
            stale.append(os.path.relpath(path, ROOT))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
            print("wrote", os.path.relpath(path, ROOT))
    for s in skipped:
        print("skipped:", s)
    if stale:
        print("stale (run sync_agents.py):", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
