"""Render the generated parts of `.agents/` and the per-harness agent shims from their sources.

    PYTHONUTF8=1 python applications/CodeMap/tools/agents/sync_agents.py [--check] [--pack applications/CodeMap/graph/pack]

The skills in `.agents/skills/<name>/SKILL.md` are written by hand and are the single source of
truth. Everything below is generated, so edit the source and run this script, never the output:

- `.claude/agents/<agent>.md`: Claude Code subagent shims (Cursor and VS Code read the same folder).
  Frontmatter from the skill; the body tells the agent which files to read first.
- `.agents/skills/ladybug-graph/references/tools.md`: the grammar and pack tool contract, from
  `remote/engine_mcp.py`, `graph/delta/pack_mcp.py` and `app/dsl.py` (Hypatia and Grothendieck).
- `.agents/skills/ladybug-graph/references/schema.md`: tables, columns, edge kinds and counts, read
  from the pack database (needs the pack).
- `.agents/skills/erdos-architect/references/tools.md`: the direct graph tool, from `remote/ladybug_mcp.py`.
- `.agents/skills/erdos-architect/references/topology.md`: repositories, layers, edge kinds, hubs and
  coupling, counted from the pack database through the same tool Erdős uses (needs the pack).
- `.agents/skills/erdos-architect/references/graph-map.md`: the system summary, the L1 index, every L2
  navigator in full and the curation notes, as XML, with membership measured from the database (needs the pack).
- `.agents/skills/erdos-architect/CLAUDE.erdos.md`: Erdős's operating manual, the SKILL.md body with every
  `<include file="references/..."/>` line replaced by that file. A harness delivers it as a CLAUDE.md (needs the pack).

`--check` renders in memory and exits 1 when a committed file differs; outputs that need the pack
are skipped (and reported) when the pack is absent. Deterministic: same inputs, same bytes.
"""

import argparse
import ast
import csv
import hashlib
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
R = os.path.dirname(os.path.dirname(HERE))                  # applications/CodeMap
ROOT = os.path.dirname(os.path.dirname(R))                   # the repository
SKILLS = os.path.join(ROOT, ".agents", "skills")
ERDOS = os.path.join(SKILLS, "erdos-architect")
MANUAL = os.path.join(ERDOS, "CLAUDE.erdos.md")
CLAUDE_AGENTS = os.path.join(ROOT, ".claude", "agents")
for p in (R, os.path.join(R, "app"), os.path.join(R, "graph", "delta"), os.path.join(R, "tools", "prompt")):
    if p not in sys.path:
        sys.path.insert(0, p)

GENERATED = "<!-- generated by applications/CodeMap/tools/agents/sync_agents.py; edit the source it names, not this file -->"
COMMENT = re.compile(r"<!--.*?-->[ \t]*\n?", re.S)
INCLUDE = re.compile(r'^[ \t]*<include file="(references/[A-Za-z0-9_.-]+\.md)"\s*/>[ \t]*$', re.M)

# agent -> the files it reads first, in order (paths relative to the repository root)
AGENTS = {
    "hypatia-indexer": [".agents/skills/ladybug-graph/SKILL.md", ".agents/skills/hypatia-indexer/SKILL.md"],
    "grothendieck-organizer": [".agents/skills/ladybug-graph/SKILL.md", ".agents/skills/grothendieck-organizer/SKILL.md"],
    "erdos-architect": [".agents/skills/erdos-architect/CLAUDE.erdos.md"],
}

# what counts as a test file when the topology is measured
TEST_FILE = ("(e.file_path CONTAINS '/src/test/' OR e.file_path ENDS WITH '.spec.ts' "
             "OR e.file_path STARTS WITH 'frontend/e2e-tests/')")


# ----------------------------------------------------------------------------- frontmatter

def split_frontmatter(text):
    """-> (fields, body). A small subset of YAML: `key: value` lines, double-quoted or bare values,
    and one level of indented `key: value` under a bare `key:` (kept as a dict)."""
    text = text.replace("\r\n", "\n")
    if not text.startswith("---\n"):
        return {}, text
    end = text.index("\n---\n", 4)
    fields, current = {}, None
    for line in text[4:end].split("\n"):
        if not line.strip():
            continue
        indented = line.startswith("  ")
        key, _, value = line.strip().partition(":")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] == '"':
            value = value[1:-1]
        if indented and current is not None:
            fields[current][key] = value
        elif value == "":
            current = key
            fields[key] = {}
        else:
            current = None
            fields[key] = value
    return fields, text[end + 5:]


def skill(name):
    with open(os.path.join(SKILLS, name, "SKILL.md"), encoding="utf-8") as f:
        return split_frontmatter(f.read())


# ----------------------------------------------------------------------------- the manual

def expand_includes(body, base=ERDOS, sources=None):
    """Replace each `<include file="references/x.md"/>` line with that file's text, comments dropped.
    `sources` maps a relative path to text rendered in this run, which wins over the file on disk."""
    def fill(m):
        rel = m.group(1)
        text = (sources or {}).get(rel)
        if text is None:
            with open(os.path.join(base, rel), encoding="utf-8") as f:
                text = f.read()
        return COMMENT.sub("", text.replace("\r\n", "\n")).strip()
    return INCLUDE.sub(fill, body)


def render_manual(body=None, sources=None):
    """-> Erdős's operating manual: the skill body (or a candidate body) with comments dropped, includes
    expanded and blank-line runs collapsed, then one checksum line (the sha256 prefix of everything above it).
    A harness asks the model for the checksum to prove the manual reached it in full, tail included."""
    if body is None:
        _, body = skill("erdos-architect")
    text = expand_includes(COMMENT.sub("", body.replace("\r\n", "\n")), sources=sources)
    text = re.sub(r"\n{3,}", "\n\n", text).strip() + "\n"
    return text + f'<manual_checksum value="{hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]}"/>\n'


# ----------------------------------------------------------------------------- renderers

def render_shim(name):
    fields, _ = skill(name)
    reads = "\n".join(f"{i}. `{p}`" for i, p in enumerate(AGENTS[name], 1))
    return (f"---\nname: {name}\ndescription: \"{fields['description']}\"\nmodel: inherit\n---\n{GENERATED}\n"
            f"<!-- source: .agents/skills/{name}/SKILL.md -->\n\n"
            f"Before anything else, read these files in full and follow them; together they are your operating manual:\n\n"
            f"{reads}\n\n"
            f"Paths are relative to the root of the graph-theory-system-modeling repository. A long file may need several "
            f"Read calls with offset and limit; read every part. When a file and this note disagree, the file wins. "
            f"Return the report or answer the manual defines.\n")


def render_tools():
    from remote.engine_mcp import TOOLS as ENGINE
    import pack_mcp
    import dsl
    out = [GENERATED, "<!-- sources: remote/engine_mcp.py, graph/delta/pack_mcp.py, app/dsl.py -->", "",
           "# The CodeMap graph tools", "",
           "Both servers are read-only stdio MCP servers over the pack; start them with `CODEMAP_PACK_DIR` set to the pack "
           "directory and an absolute script path (Claude Code does not honour a working directory in an MCP config).", "",
           "## engine (`applications/CodeMap/remote/engine_mcp.py`)", ""]
    for t in ENGINE:
        out.append(f"- **`{t['name']}`**({', '.join(t['inputSchema']['properties'])}) — {t['description']}")
    out += ["", "## pack (`applications/CodeMap/graph/delta/pack_mcp.py`)", ""]
    for t in pack_mcp.TOOLS:
        out.append(f"- **`{t['name']}`**({', '.join(t['inputSchema']['properties'])}) — {t['description']}")
    out += ["", "## Verbs for `engine_step`", "", "| verb | arguments |", "|---|---|"]
    for verb, arity in dsl.VERBS.items():
        if verb in ("answer", "pass", "cache"):
            continue
        args = {0: "none", 1: "one", 2: "two"}.get(arity, "one or two") if not isinstance(arity, tuple) else f"{arity[0]} or {arity[1]}"
        out.append(f"| `{verb}` | {args} |")
    out += ["", "`health` takes `coupling` (subsystems by external ratio) or `hubs` (entities by in-degree). "
                "`answer`, `pass` and `cache` belong to the served navigator's loop and are not for agents.", ""]
    return "\n".join(out)


def render_graph_tool():
    from remote import ladybug_mcp
    t = ladybug_mcp.TOOLS[0]
    return "\n".join([
        GENERATED, "<!-- source: applications/CodeMap/remote/ladybug_mcp.py -->", "",
        f'<tool name="mcp__graph__{t["name"]}" server="graph" script="applications/CodeMap/remote/ladybug_mcp.py">',
        t["description"],
        'Input: {"statement": "<one Cypher statement>"}. Output: JSON {"columns", "rows", "row_count", "truncated"}, '
        'or {"error"} carrying the database\'s own message.',
        f"Limits: {ladybug_mcp.MAX_ROWS} rows and {ladybug_mcp.MAX_CHARS:,} characters per answer (row_count stays the full "
        f"count), {ladybug_mcp.TIMEOUT_MS // 1000} seconds per statement. The database is opened read-only.",
        "</tool>", ""])


def render_schema(pack):
    import real_ladybug as lb
    db = lb.Database(os.path.join(pack, "codemap.lbdb"), read_only=True)
    con = lb.Connection(db)

    def rows(stmt):
        r = con.execute(stmt)
        out = []
        while r.has_next():
            out.append(r.get_next())
        return out

    man = json.load(open(os.path.join(pack, "manifest.json"), encoding="utf-8"))
    out = [GENERATED, "<!-- source: the pack database and manifest -->", "", "# Pack schema", "",
           f"Pack `{man.get('pack_version')}`, built `{man.get('built_at')}`, dialect `{man.get('dialect')}`.", "",
           "Indexed commits: " + ", ".join(f"{k} `{v}`" for k, v in sorted((man.get("indexed_sha") or {}).items())) + ".", "",
           "## Tables", ""]
    for _, name, kind, _, _ in sorted(rows("CALL show_tables() RETURN *"), key=lambda r: r[1]):
        out += [f"### `{name}` ({kind.lower()})", "", "| column | type | primary key |", "|---|---|---|"]
        for info in rows(f"CALL table_info('{name}') RETURN *"):
            pk = info[4] if isinstance(info[4], bool) else ""
            out.append(f"| `{info[1]}` | {info[2]} | {'yes' if pk is True else ''} |")
        out.append("")
    out += ["## Counts", "", "| what | n |", "|---|---|"]
    for k, v in sorted((man.get("counts") or {}).items()):
        out.append(f"| {k} | {v} |")
    out += ["", "## Edge kinds (`Dep.rel`)", "", "| rel | edges |", "|---|---|"]
    for rel, n in sorted(rows("MATCH (:Entity)-[r:Dep]->(:Entity) RETURN r.rel, count(*)"), key=lambda r: (-r[1], r[0])):
        out.append(f"| `{rel}` | {n} |")
    out += ["", "## Entity layers", "", "| layer | entities |", "|---|---|"]
    for layer, n in sorted(rows("MATCH (e:Entity) RETURN e.layer, count(*)"), key=lambda r: (-r[1], str(r[0]))):
        out.append(f"| `{layer}` | {n} |")
    out += ["", "## CSV headers", ""]
    for name in ("entities.csv", "edges.csv", "edges_lb.csv", "hyperedges.csv"):
        path = os.path.join(pack, name)
        if os.path.exists(path):
            with open(path, encoding="utf-8", newline="") as f:
                out.append(f"- `{name}`: {', '.join(next(csv.reader(f)))}")
    out.append("")
    return "\n".join(out)


class _Graph:
    """The pack seen through the direct graph tool: workspace paths, the same dialect Erdős writes."""

    def __init__(self, pack):
        from remote import ladybug_mcp
        self.tools = ladybug_mcp.GraphTools(pack_dir=pack)
        self.max_rows = ladybug_mcp.MAX_ROWS

    def rows(self, stmt):
        text, err = self.tools.query(stmt)
        out = json.loads(text)
        if err or out["truncated"]:
            raise RuntimeError(f"topology query failed or was truncated: {stmt}: {out.get('error') or out['row_count']}")
        return out["rows"]


def _items(value):
    """A navigator field as a list: lists pass through; JSON or Python-literal strings are decoded."""
    if value in (None, "", "[]"):
        return []
    if isinstance(value, (list, tuple)):
        return list(value)
    if isinstance(value, str):
        for parse in (json.loads, ast.literal_eval):
            try:
                parsed = parse(value)
            except (ValueError, SyntaxError):
                continue
            return list(parsed) if isinstance(parsed, (list, tuple)) else [parsed]
    return [value]


def _attr(value):
    return str(value).replace('"', "'").replace("\n", " ")


def _navigators(pack):
    with open(os.path.join(pack, "l2_navigators.jsonl"), encoding="utf-8") as f:
        return {int(n["sub_id"]): n for n in (json.loads(line) for line in f if line.strip())}


def render_topology(pack):
    g = _Graph(pack)
    man = json.load(open(os.path.join(pack, "manifest.json"), encoding="utf-8"))
    navs = _navigators(pack)
    name = {sid: n.get("name", "?") for sid, n in navs.items()}
    sha = man.get("indexed_sha") or {}
    repo = "CASE WHEN e.file_path STARTS WITH 'backend/' THEN 'backend' ELSE 'frontend' END"

    out = [GENERATED, "<!-- source: the pack database and manifest, read through applications/CodeMap/remote/ladybug_mcp.py -->", "",
           f'<pack version="{man.get("pack_version")}" built_at="{man.get("built_at")}" '
           + " ".join(f'{k}_commit="{v[:12]}"' for k, v in sorted(sha.items())) + "/>", ""]

    ents = dict(map(tuple, g.rows(f"MATCH (e:Entity) RETURN {repo} AS repo, count(*) ORDER BY repo")))
    eps = dict(map(tuple, g.rows(f"MATCH (e:Entity) WHERE e.entry_point RETURN {repo} AS repo, count(*) ORDER BY repo")))
    src = dict(map(tuple, g.rows(f"MATCH (e:Entity)-[r:Dep]->(:Entity) RETURN {repo} AS repo, count(*) ORDER BY repo")))
    cross = g.rows("MATCH (a:Entity)-[r:Dep]->(b:Entity) WHERE (a.file_path STARTS WITH 'backend/' AND b.file_path STARTS WITH 'frontend/') "
                   "OR (a.file_path STARTS WITH 'frontend/' AND b.file_path STARTS WITH 'backend/') RETURN count(*)")[0][0]
    out += ["<repositories>", "| repository | entities | entry points | edges starting there |", "|---|---|---|---|"]
    for r in ("backend", "frontend"):
        out.append(f"| {r} | {ents.get(r, 0)} | {eps.get(r, 0)} | {src.get(r, 0)} |")
    out += [f"| total | {sum(ents.values())} | {sum(eps.values())} | {sum(src.values())} |",
            f"Edges between the two repositories: {cross}.", "</repositories>", ""]

    kinds = g.rows("MATCH (e:Entity) RETURN CASE WHEN e.name CONTAINS '.' THEN list_reverse(string_split(e.name, '.'))[1] "
                   "ELSE 'directory' END AS kind, count(*) AS n ORDER BY n DESC, kind")
    out += ["<file_kinds>", " · ".join(f"{k} {n}" for k, n in kinds), "</file_kinds>", ""]

    layers = g.rows("MATCH (e:Entity) RETURN e.layer, count(*) ORDER BY e.layer")
    by_repo = {(l, r): n for l, r, n in g.rows(f"MATCH (e:Entity) RETURN e.layer, {repo} AS repo, count(*)")}
    tests = dict(map(tuple, g.rows(f"MATCH (e:Entity) WHERE {TEST_FILE} RETURN e.layer, count(*)")))
    lay_eps = dict(map(tuple, g.rows("MATCH (e:Entity) WHERE e.entry_point RETURN e.layer, count(*)")))
    heights = {l: h for l, h in g.rows("MATCH (e:Entity) WHERE e.local_height IS NOT NULL RETURN e.layer, round(avg(e.local_height), 2)")}
    no_height = dict(map(tuple, g.rows("MATCH (e:Entity) WHERE e.local_height IS NULL RETURN e.layer, count(*)")))
    out += ["<layers>", "| layer | entities | backend | frontend | test files | entry points | mean local_height | without a height |",
            "|---|---|---|---|---|---|---|---|"]
    for layer, n in sorted(layers, key=lambda r: heights.get(r[0], 9)):
        out.append(f"| {layer} | {n} | {by_repo.get((layer, 'backend'), 0)} | {by_repo.get((layer, 'frontend'), 0)} | "
                   f"{tests.get(layer, 0)} | {lay_eps.get(layer, 0)} | {heights.get(layer, '')} | {no_height.get(layer, 0)} |")
    out += ["</layers>", ""]

    total = g.rows("MATCH (:Entity)-[r:Dep]->(:Entity) RETURN r.rel, count(*) AS n ORDER BY n DESC, r.rel")
    rel_repo = {(rel, rp): n for rel, rp, n in g.rows(f"MATCH (e:Entity)-[r:Dep]->(:Entity) RETURN r.rel, {repo} AS repo, count(*)")}
    pairs = {}
    for rel, a, b, n in g.rows("MATCH (a:Entity)-[r:Dep]->(b:Entity) RETURN r.rel, a.layer, b.layer, count(*) AS n"):
        pairs.setdefault(rel, []).append((n, f"{a} → {b}"))
    out += ["<edge_kinds>", "| rel | edges | from backend | from frontend | commonest layer pairs (from → to) |", "|---|---|---|---|---|"]
    for rel, n in total:
        top = ", ".join(f"{p} {c}" for c, p in sorted(pairs.get(rel, []), key=lambda x: (-x[0], x[1]))[:3])
        out.append(f"| {rel} | {n} | {rel_repo.get((rel, 'backend'), 0)} | {rel_repo.get((rel, 'frontend'), 0)} | {top} |")
    out += ["</edge_kinds>", ""]

    hubs = g.rows("MATCH (d:Entity)-[:Dep]->(e:Entity) RETURN e.file_path, e.layer, coalesce(e.curated, e.subsystem) AS sub, "
                  "count(*) AS incoming ORDER BY incoming DESC, e.file_path LIMIT 20")
    out += ["<hubs>", "| entity | layer | subsystem | incoming edges |", "|---|---|---|---|"]
    for path, layer, sub, n in hubs:
        out.append(f"| {path} | {layer} | [{sub}] {name.get(sub, '?')} | {n} |")
    out += ["</hubs>", ""]

    coupling = g.rows("MATCH (a:Entity)-[r:Dep]->(b:Entity) WITH coalesce(a.curated, a.subsystem) AS src, coalesce(b.curated, b.subsystem) AS dst "
                      "WHERE src <> dst RETURN src, dst, count(*) AS edges ORDER BY edges DESC, src, dst LIMIT 20")
    out += ["<coupling>", "| from subsystem | to subsystem | edges |", "|---|---|---|"]
    for a, b, n in coupling:
        out.append(f"| [{a}] {name.get(a, '?')} | [{b}] {name.get(b, '?')} | {n} |")
    out += ["</coupling>", ""]
    return "\n".join(out)


def _render_navigator(sid, nav, measured, lay):
    role = nav.get("role", "?")
    attrs = [f'id="{sid}"', f'name="{_attr(nav.get("name", "?"))}"', f'role="{role}"']
    if nav.get("parent") not in (None, "", "None"):
        attrs.append(f'group="{nav.get("parent")}"')
    if role == "GROUP":
        attrs.append(f'children="{" ".join(str(c) for c in nav.get("children") or [])}"')
    else:
        attrs.append(f'files="{measured.get(sid, 0)}"')
        profile = ", ".join(f"{k} {v}" for k, v in sorted(lay.get(sid, {}).items(), key=lambda kv: (-kv[1], kv[0])))
        if profile:
            attrs.append(f'layers="{profile}"')
    lines = [f"<subsystem {' '.join(attrs)}>"]
    if nav.get("ai_summary"):
        lines.append(f"summary: {nav['ai_summary'].strip()}")
    does = _items(nav.get("responsibilities"))
    if does:
        lines.append("does:")
        lines += [f"- {str(x).strip()}" for x in does]
    eps = _items(nav.get("entry_points"))
    if eps:
        lines.append("entry points: " + "; ".join(str(x) for x in eps))
    spines = [s for s in _items(nav.get("spines")) if isinstance(s, dict)]
    if spines:
        lines.append("spines: " + "; ".join(f"{s.get('metapath')} through {s.get('hub')}" for s in spines))
    contracts = [c for c in _items(nav.get("contracts")) if isinstance(c, dict)]
    if contracts:
        lines.append("contracts: " + "; ".join(
            f"{c.get('rel')} {'to' if c.get('dir') == 'out' else 'from'} [{c.get('other')}] {c.get('n')} edges" for c in contracts))
    cav = _items(nav.get("caveats"))
    if cav:
        lines.append("caveats:")
        lines += [f"- {str(x).strip()}" for x in cav]
    lines.append("</subsystem>")
    return "\n".join(lines)


def render_graph_map(pack):
    g = _Graph(pack)
    navs = _navigators(pack)
    l1 = json.load(open(os.path.join(pack, "l1_master.json"), encoding="utf-8"))
    measured = dict(map(tuple, g.rows("MATCH (e:Entity) RETURN coalesce(e.curated, e.subsystem) AS sub, count(*)")))
    lay = {}
    for sub, layer, n in g.rows("MATCH (e:Entity) RETURN coalesce(e.curated, e.subsystem) AS sub, e.layer, count(*)"):
        lay.setdefault(sub, {})[layer] = n
    notes_path = os.path.join(pack, "curation_notes.md")
    notes = open(notes_path, encoding="utf-8").read().replace("\r\n", "\n").strip() if os.path.exists(notes_path) else "none"
    notes = re.sub(r"^## Curation notes\n+", "", notes)
    out = [GENERATED, "<!-- source: the pack (l1_master.json, l2_navigators.jsonl, curation_notes.md) with membership counted from the database -->", "",
           "<system_summary>", (l1.get("ai_summary") or "").strip(), "</system_summary>", "",
           "<subsystem_index>", (l1.get("subsystem_index") or "").strip(), "</subsystem_index>", "",
           "<global_caveats>"]
    out += [f"- {str(c).strip()}" for c in _items(l1.get("global_caveats"))]
    out += ["</global_caveats>", "", "<subsystems>"]
    for sid in sorted(navs):
        nav = navs[sid]
        if nav.get("routable") is False:
            into = (nav.get("superseded_by") or ["?"])[0]
            out.append(f'<merged id="{sid}" name="{_attr(nav.get("name", "?"))}" into="{into}"/>')
            continue
        out.append(_render_navigator(sid, nav, measured, lay))
    out += ["</subsystems>", "", "<curation_notes>", notes, "</curation_notes>", ""]
    return "\n".join(out)


# ----------------------------------------------------------------------------- targets

def targets(pack):
    """-> ({path: text}, [skipped reasons])."""
    out, skipped = {}, []
    for name in AGENTS:
        out[os.path.join(CLAUDE_AGENTS, f"{name}.md")] = render_shim(name)
    out[os.path.join(SKILLS, "ladybug-graph", "references", "tools.md")] = render_tools()
    out[os.path.join(ERDOS, "references", "tools.md")] = render_graph_tool()
    if pack and os.path.exists(os.path.join(pack, "codemap.lbdb")):
        out[os.path.join(SKILLS, "ladybug-graph", "references", "schema.md")] = render_schema(pack)
        refs = {"references/tools.md": out[os.path.join(ERDOS, "references", "tools.md")],
                "references/topology.md": render_topology(pack),
                "references/graph-map.md": render_graph_map(pack)}
        for rel, text in refs.items():
            out[os.path.join(ERDOS, *rel.split("/"))] = text
        out[MANUAL] = render_manual(sources=refs)
    else:
        skipped.append(f"no pack at {pack}: schema.md, topology.md, graph-map.md and CLAUDE.erdos.md not rendered")
    return out, skipped


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--pack", default=os.path.join(R, "graph", "pack"))
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    files, skipped = targets(a.pack)
    stale = []
    for path, text in sorted(files.items()):
        current = open(path, encoding="utf-8").read().replace("\r\n", "\n") if os.path.exists(path) else None
        if current == text:
            continue
        if a.check:
            stale.append(os.path.relpath(path, ROOT))
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
            print("wrote", os.path.relpath(path, ROOT))
    for s in skipped:
        print("skipped:", s)
    if stale:
        print("stale (run sync_agents.py):", ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
